### ISSUE TITLE
[Question] How did you write the code?

### ISSUE THREAD

**Issue by nopara73** [Ayms/node-Tor#13]
What specificaiton/code did you follow? I've been long wanting to code it myself, but there's a lot of outdated spaghetti out there, so I always failed.

**Comment by Ayms** [comment]
I wrote the code by myself following the Tor project docs/specs and using the dependencies listed, what do you mean by "outdated spaghetti"?

**Comment by nopara73** [comment]
> what do you mean by "outdated spaghetti"?

Tor is an old software project with a lot of historical context. Most specs and docs I encountered are old and often come with addendums on different docs those also sometimes invalidate or change parts of the previous docs. I wouldn't mind the dated docs, but it makes me cautious, if there's one thing all software developer knows: what's said yesterday is not going to be true tomorrow:)
I personally manage to work well with the Tor process, but other than a few bugs I needed to track down the thing is a black box for me.

Would you mind pointing me to the relevant docs/specs that'd let me get started with building up a connection to a v3 hidden server without using the Tor process?  

Btw, I just checked, are you really working on this since 2012? If so, congrats on the persistence!

**Comment by Ayms** [comment]
Yes and thanks, since 2012... but not obsolete at all, was more difficult at that time to put everything inside browsers (or even nodejs)

You are right Tor docs are not always straight forward and sometimes not detailed enough (then you have to look in their tentacular code...not easy...) but they are usually clear enough for most of the work to be done, I used the docs in https://2019.www.torproject.org/docs/documentation.html.en, maybe this is not what you are looking for ("Tor process") but I am not aware of any other docs more clear and detailed enough, only general presentations

**Comment by nopara73** [comment]
Yes, I am aware of those docs, I was hoping for a silver bullet instead :)

Thank you!

**Comment by Ayms** [comment]
Unfortunately I don't have magic docs :-)

But maybe the best doc is to look into the node-Tor code, the Tor protocol part was not easy to implement but is not the most complicate one in node-Tor, even it's simple once it's done (or you can look at the initial commit, more simple)
