### ISSUE TITLE
[Question] on client<->client communication

### ISSUE THREAD

**Issue by tobowers** [Ayms/node-Tor#14]
Let me know if there is a better channel to ask these questions (IRC, Discord, etc)

This project looks really cool and I'm interested in exploring using it and/or contributing. The docs aren't complete (totally understandable) and the code is tricky for a new-comer at first glance... though I think I might understand it.

1. I'm trying to see how two clients could communicate a stream of data. browser2.js looks interesting, but It seems to only be for getting/sending content? Is is it possible to send/receive data directly?

2. Can you access Tor onion sites through node-tor?

3. it looks like right now the browser just talks WS to a bridge? Is the webrtc implemented? What's the plan for the browser to connect directly?

4. Can I create a Tor onion service through node-tor?

Any pointers directly to code would be appreciated... basically I want to explore using node-tor to implement edge compute on p2p networks and getting past the nasty NAT/install issues that entails - very similar to your convergence paper.

**Comment by Ayms** [comment]
Thanks for your interest and yes this is the right place to discuss, probably you have seen https://github.com/Ayms/node-Tor#forking-node-tor which is answering most of your concerns, I hope to release it soon

So indeed the code (even splitted into modules) is not obvious right now (even for myself :-) ) and the docs are a bit short

node-Tor is well designed, then once the pipe methods are implemented it will be much more clear and the different layers clearly splited, then you can easily do (following the detailed docs coming with the code) : ``(client any protocol).pipe(whatever protocol).pipe(node-Tor).pipe(RDV - optional)`` both on client/serving side and both on server/browser side

1- I think the above answers this point

2- No and it is not foreseen, while probably easy to implement, because I don't see the point, neither the use case and using onion addresses does not look logical, instead the RDV mechanism is implemented which allows peers to connect to a RDV point where other peers advertise what they are doing using simply a hash, then the RDV point will connect the peers randomely (example : ``ipfs.pipe(node-Tor).pipe(RDV)`` where the ipfs peers are using a fixed hash to tell that they are implementing ipfs), maybe it can look too simple but this can of course be discussed/changed

3- indeed, you can use also XHR or socks but the later being of course not recommended from the browsers, there is a funding proposal ongoing to fund the dev of elliptic crypto and webRTC, it will support Snowflake but will do much more allowing the Tor protocol between WebRTC peers via anonymized circuits between browser peers, via a RDV point also or not

4- Yes but not the Tor project way, cf above, again this can be discussed according to the needs and level of security required

Glad to see that someone read the Convergence paper +1: it's from 2015 so I would update some parts but if everything written above happens then we are getting quite close to the convergence concepts (and in fact universal and easy use/add of the Tor protocol for/to any protocol/network inside browsers or nodes)

**Comment by tobowers** [comment]
Thanks for the comments. Is there any preview release or half-developed code for the pipes? I'd love to play around with it (pre-production).

I just learned about Snowflake :) ( https://snowflake.torproject.org/ ) for those following along. 

I'm also just understanding that RDV is rendezvous point - got it now. 

I like the way libp2p splits up application from transport ( https://docs.libp2p.io/concepts/transport/ ) and I think this project could be really nice as a replacement for the IPFS DHT and also the libp2p p2p transport at the minimum in browsers.

I'm just wondering if there's some way I can contribute / play with something to create simple client <-> client applications now or do I have to wait for phase 4 ? :).

My team and I also have some experience with webrtc and ECC as well.

**Comment by Ayms** [comment]
Noted for RDV, I will make it more clear, of course RDV points are only needed if peers want to hide their activity, you can pipe from peers to peers via anonymized circuits directly

For libp2p I don't know in fact, the goal for node-Tor is to turn ``whatever protocol`` into a duplex stream following the node-Tor specs, like sketched in https://github.com/ipfs/ipfs/issues/439#issuecomment-570470538 as you know

Thanks for the contribution proposal, for now I think it's better to wait (because I have discovered also some bugs with what is in the repo but will not update it before pipe is released, the peersm2 code is updated), however you can still practice a bit if you like, the principle is always the same: ``Tor(request)`` where request is used to create circuits or to manage a protocol (via for example ``request._write_``), the pipe methods are just splitting ``request`` among the different layers but it's not as trivial as it could look like, so I cannot release for now pre-production code, a client to client application exists in peersm2 demo, downloading content from a peer to another one via a RDV point (ORDB) and a infohash

But to summarize, I think you should wait a bit in fact

**Comment by Ayms** [comment]
Referencing this https://github.com/webtorrent/webtorrent/issues/1767 also

**Comment by Ayms** [comment]
@tobowers the evented pipe methods are now released and the detailed docs also, please see https://github.com/Ayms/node-Tor/tree/master/docs

It's still experimental and not fully tested but looks to be working well, phase 5 depends on the funding

**Comment by tobowers** [comment]
Amazing. Thanks! I'll take a look.

**Comment by Ayms** [comment]
Closing... unfortunately... phase 4 (evented pipe methods) has been rollbacked and is not open source

https://github.com/ipfs/ipfs/issues/439#issuecomment-602086873
