### ISSUE TITLE
Using node-Tor to access a TOR hidden service

### ISSUE THREAD

**Issue by pajasevi** [Ayms/node-Tor#15]
Hi, I have to say that this is amazing work but I am unable to fully grasp what do I need to do in order to achieve my goal.

I have an API which is accessible as a Tor hidden service and I need to send GET/POST requests to this API from node.js server. And I can't use native Tor binary and use a socks proxy.

From what I was able to understand, I don't have to publish my node but updating the routers should be done periodically.
Can you please help me understand what are the minimal steps to run requests through node-Tor to the hidden service?

Thank you

**Comment by Ayms** [comment]
Hi,

node-Tor does not support hidden services, because we don't see the use case and use of onion like addresses is really specific to the Tor network, instead it does support the RDV protocol

I am not sure to understand very well what you are trying to do, what prevents you from setting up a Tor project node on your nodejs server and send requests through it to your hidden service?

**Comment by pajasevi** [comment]
Well the use case is simple: uncensorable web services that are able to run anywhere, independent of the IP address.

What prevents me is that I am using Electron to build a desktop app and bundling it with Tor executable for several operating systems seems to be a big issue.

Thank you for your answer.

**Comment by Ayms** [comment]
What I meant with the use case it that there is no point to use onion addresses, the RDV protocol does the same than hidden services without this

I am afraid that if you use the Tor network hidden services then you must proxy your electron app to the Tor project sw (the localhost socks proxy, if I understand correctly your issue is to bind the whole thing together for different os)

It is true that node-Tor could handle that case but does not

**Comment by pajasevi** [comment]
Well, thank you anyway, I'll keep a look on this repo 😉
