### ISSUE TITLE
Http request

### ISSUE THREAD

**Issue by QuentinANIERE** [Ayms/node-Tor#16]
It is possible to use Node-Tor to perform simple http request  ? I planned to make React Native Tor Chat, so I cant use the tor official client

**Comment by Ayms** [comment]
Yes, see https://github.com/Ayms/node-Tor/blob/master/lib/src/browser2.js#L706 , this is part of the demo app which is deactivated for now (because the project is between two phases awaiting some funding to finalize the evented pipe methods where http will be clearly splitted)

**Comment by QuentinANIERE** [comment]
Great! So all I have to do is install NodeTor, call the load function and that's it?

**Comment by Ayms** [comment]
Yes and no, you must modify the load function since it mixes things with the demo app, you must setup correctly the properties of the ``request`` object and then call ``Tor(request)``

I don't know if you have some short delays but if not it would probably make sense to wait a bit for phases 4 (eventend pipe so you simply do ``http.pipe(node-Tor)`` ) and 5 (elliptic crypto)

**Comment by QuentinANIERE** [comment]
It's not a project that would succeed in the short term so, I think I can get out of phase 4, thank you very much :)
