### ISSUE TITLE
Make a usable demo page

### ISSUE THREAD

**Issue by robertsdotpm** [Ayms/node-Tor#18]
Hello, this project greatly interests me. It seems that there was at one point a demo but it was removed? I might be willing to pick this up if someone were to at least show how to use the software. If this supposedly works with web sockets surely this could be hosted somewhere for people to look at the demo? That way people could see the software works and have a starting point to look at the code. As it stands, I can't see anyone jumping in without at least that.

**Comment by robertsdotpm** [comment]
> 
> 
> Please see #17
> 
> The project is stuck between phase 3 and 4 (evented pipe methods), because of lack of financing, whether people like it or not that's how it is
> 
> And the demo page has been removed because of this, not supporting a half finished work, now the docs are very detailed and you can easily use the current version, including ws which does not "supposedly work" but just work, look at the docs again, it's not difficult

Thanks for the reply Ayms. I wanted to say I think this project is hugely under rated and has the potential to change how the Internet works. I understand you've run out of funds to continue which is understandable. I'd like to offer you a small amount of money to add demos for the functionality that works at the moment. I know you say there are docs but as someone new to the project they are very long and technical. I really can't see a starting point or make much sense of them.

I think since this is all designed to run in a browser that simple websites show-casing various functionality would be the best way to get new developers involved. I can't fund full time development by myself but I can contribute some spare funds from my salary. Starting with 2k usd to get some basic HTML demos up. Let me know what you think.

**Comment by Ayms** [comment]
Thanks for your comments, indeed this project has a huge potential and many applications

I cannot ask yourself to fund it, even just to setup the demo page, and the problem is that it would be something like a waste of time because the demo page was not working very well for phase 3 since this was not the main target of the complete repackaging of node-Tor, maybe that's the reason why the funding did not continue

Now I am still trying to get some funding to finish/release phase 4 and the associated demo page, so maybe we should wait a little bit

The docs are a bit long but give all the details, so to setup the demo  page you can run your OR and ORDB as described in the docs and load index.html inside the browser (after modifying one_OR and DB_OR as explained here https://github.com/Ayms/node-Tor#browserify and upadting guards and exit.js)

**Comment by Mohsen7s** [comment]
@robertsdotpm Check this if you are willing to fund the project with a small amount of money.
[https://github.com/Ayms/node-Tor/issues/19](https://github.com/Ayms/node-Tor/issues/19)
