### ISSUE TITLE
How to use it on a site ?

### ISSUE THREAD

**Issue by albabosh** [Ayms/node-Tor#7]
Can I put this project onto my site so I could download books from torrents ? Is there any api ?

**Comment by Ayms** [comment]
Theorically yes but in practice that's difficult, please see https://github.com/Ayms/node-Tor/tree/master/install, there is no API, you can use what is in the node-Tor repo but the code is not open source (except the initial commit)

**Comment by albabosh** [comment]
I see it is not opensource, but my question is "Can I start several public Node-tor gateways, and then put a client on my site so visitors can use it as well as www.peersm.com ?"

**Comment by Ayms** [comment]
Late answer because I had to remind a little bit how everything works

Unfortunately the answer is no:

You can create a bridge, then connect to it with peersm app code using ``http://peersm_code/#IP:port

Then you can install a peersm client to bridge with bittorrent, then you must hack in the code the url http://peersm.com/peersmclient/proxy.pac so you can modify arg[1] the ws bridge where the peersm client will connect to and arg[2] the ordb server

But the ordb server code is not public... so you can't install ordbs

Will make all this stuff open/public if one day someone(s) has some little intention to finance it

**Comment by knoxcard** [comment]
Financing, how much is required?

**Comment by Ayms** [comment]
If I can get 20-30 KE or 4-5 BTCs then I will put everything public and open source

**Comment by jonathancross** [comment]
> but the code is not open source...

Can you clarify?  Looks like it is now?

**Comment by Ayms** [comment]
Yes, it is now, modular and in clear, see http://peersm.com/peersm2 for the demo and how to use the code (see browser2.js and the README)
